### ISSUE TITLE
Documentation: does the non-recompilation depend on the variables being inserted in a C file?

### ISSUE THREAD

**Issue by jaskij** [andrew-hardin/cmake-git-version-tracking#48]
I want to put the variables obtained from the git_watcher script into a header file. Between the documentation and examples, I'm not entirely sure if this will still not trigger recompilation until something actually changes.

**Comment by andrew-hardin** [comment]
That's a good question. Embedding the variables in a header won't trigger a recompilation until one of the macros change (... because the values passed to the compile command changed).

Embedding the macros in a `.c/.cpp` file instead of a header isolates recompilation to just a single `.o` file (+ any downstream re-linking).

**Comment by jaskij** [comment]
Thanks for the explanation. That puts me at ease. I'm using C++ `constexpr` and rely on inlining heavily, and using your examples directly would've ran counter to the rest of the codebase.
